image: docker:stable

services:
  - docker:dind

stages:
  - docker-test
  - docker-build

variables:
  DOCKER_IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

docker-test:
  stage: docker-test
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker run $DOCKER_IMAGE_TAG go test ./calc

docker-build:
  stage: docker-build
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE_TAG
  only:
    - master
    - main
