image: golang:1.20-alpine

stages:
  - build
  - test

before_script:
  - go mod tidy
  - go mod download

build:
  stage: build
  script:
    - go build -o /main
  artifacts:
    paths:
      - main

test:
  stage: test
  script:
    - go test ./calc