# Stage 1: Build the application
FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY . ./

RUN go mod download && go mod tidy

RUN go build -o /main

# Stage 2: Create the final lightweight image
FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=builder /main /main

EXPOSE 8080

CMD ["/main"]
